### ISSUE TITLE
"Loading Data..." indicator never goes away

### ISSUE THREAD

**Issue by mormond** [dxuk/UKOfficeHours#10]
After adding a new slot, the "Loading Data..." indicator is permanently displayed

![snip_20170328150516](https://cloud.githubusercontent.com/assets/13424886/24409471/34a02410-13c8-11e7-8c65-a0573e875824.png)

**Comment by WillEastbury** [comment]
Yes, this is definitely a bug where the loading graphic is being invoked at an inappropriate time.

I have fixed this in the Add a slot screen, but the Add an ISV screen is still suffering from the same issue.

**Comment by WillEastbury** [comment]
Fixed in current build deployed to CI.
