### ISSUE TITLE
Add a slot start time - increment in 15min chunks

### ISSUE THREAD

**Issue by mormond** [dxuk/UKOfficeHours#11]
It would be nice if the Add a slot -> Start Time could be incremented in 15min chunks (or even 5mins) rather than 1min. Sessions will usually start on either the hour or half-hour. On the odd occasion they don't, the can be manually edited.

![snip_20170328151041](https://cloud.githubusercontent.com/assets/13424886/24409649/bf030fc8-13c8-11e7-8271-76043d425eb4.png)

**Comment by WillEastbury** [comment]
Hi Mike,

If you click on the minute number instead of using the up and down arrows to select, the picker control will drill out to a 5-minute selector style, which should be what you want to do. 

I'll make sure this is made clear in the training notes we put together ! 

Thanks,
Will
