### ISSUE TITLE
Month / Month Filter Issue

### ISSUE THREAD

**Issue by mormond** [dxuk/UKOfficeHours#12]
It's dummy data I know - and probably the cause here - but the months display in different formats and thus make it difficult to filter.

![snip_20170328151330](https://cloud.githubusercontent.com/assets/13424886/24409817/3ed8eb96-13c9-11e7-9c74-1c5ed2a7f4aa.png)

**Comment by WillEastbury** [comment]
That's exactly right, this will be fixed in the final production data upload, you should only see the 2017 xx entries that will sort correctly.

**Comment by WillEastbury** [comment]
I've cleansed the data in CO so you can see how it SHOULD look in a prod system :)
