### ISSUE TITLE
No Current Local Debugging configuration in the repo

### ISSUE THREAD

**Issue by WillEastbury** [dxuk/UKOfficeHours#16]

**Comment by WillEastbury** [comment]
At the moment you can’t debug the service locally on your machine AT ALL.

You should be able to have an override switch somewhere in the auth function that lets you disable auth, and then you’d be able to host the local instance of the site HTML in IIS / Express and the functions middle tier in FUNC.exe (or even connecting directly to the LO- deployed middle tier.

Basically at the moment it’s a pain to debug the javascript locally without deploying it… I’d like to fix that and keep the CI automation features that broke that in the first place …

**Comment by mormond** [comment]
Running **configure-local-debug.ps1** in the root folder will now setup a local debug environment
 - Starts the Azure Storage Emulator
 - Starts IIS Express to host the website 
 - Starts Func.exe to host the functions
 
Everything will run locally. There is a JSON config file in wwwroot which is read by both the PS script and the website.
