### ISSUE TITLE
Unable to create Booking Code

### ISSUE THREAD

**Issue by ross-p-smith** [dxuk/UKOfficeHours#29]
Need to reproduce

**Comment by mormond** [comment]
It certainly seems that if the same user attempts to create more than one slot with the same ISV name, it will fail and the UI will show the progress bar stuck "updating"

**Comment by mormond** [comment]
I'm going to look at modifying the table to change the partition / row key to allow multiple slots to be added. We'd then need to look at how we track / alert users to this.
